config/routes.rb
CatsInc::Application.routes.draw do

  # Leave this line here. It's for devise.
  devise_for :users

  # Add the nessessary routes here.
  
  # Map /items to the path controller items and action/view index
  get "/items", to: "items#index"

  get "/items/:id", to: "items#show"

# Named routes make it easier for you to see
  get "/homepage/", to: "homepage#index"

  # The DELETE verb is used when deleting from a page
  delete "/stockalerts/:id", to: "stock_alerts#destroy"
 
 # Named route 
  get "/stockalerts/:id", to: "stock_alerts#show", as: :stock_alert 
  post "/stockalerts/", to: "stock_alerts#create"
  
  post "/purchases", to: "purchases#create", as: :item 
  
  get "/admin/dashboard", to: "admin/dashboard#index" 
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base

  belongs_to :user
  belongs_to :item

end

app/models/stock_alert.rb
class StockAlert < ActiveRecord::Base

  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :purchases
  has_many :stock_alerts
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController

  before_filter :authenticate_user!

  def index
    redirect_to '/' unless current_user.is_admin?
    @recent_purchases = Purchase.order(created_at: :desc).limit(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  def index
    @items = Item.where(promoted: true).limit(5)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  before_filter :authenticate_user!

  def create
    @purchase = Purchase.new
    item = Item.find(params[:item_id])
    @purchase.item = item
    @purchase.user = current_user

    if @purchase.save
      redirect_to item_path(item), notice: 'Purchase was successfully created.'
    else
      redirect_to item_path(item), warning: "Could not process your purchase."
    end
  end

end

app/controllers/stock_alerts_controller.rb
class StockAlertsController < ApplicationController
  before_filter :authenticate_user!

  def show
    @stock_alert = StockAlert.find(params[:id])
  end

  def create
    @stock_alert = StockAlert.new
    item = Item.find(params[:item_id])
    @stock_alert.item = item
    @stock_alert.user = current_user

    if @stock_alert.save
      redirect_to @stock_alert, notice: 'Stock alert was successfully created.'
    else
      redirect_to @stock_alert.item, warning: 'Could not create that stock alert.'
    end
  end

  def destroy
    @stock_alert = StockAlert.find(params[:id])
    @stock_alert.destroy
    redirect_to @stock_alert.item
  end

  private
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/stock_alerts_helper.rb
module StockAlertsHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Admin view</h1>

<h2>Recent Purchases</h2>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Item</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recent_purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.user_id %></td>
        <td><%= purchase.item_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/homepage/index.html.erb
<h1>Cat,s Inc</h1>
<p>Buy stuff!</p>

<h2>Popular items</h2>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, item %></li>
  <% end %>
</ul>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Amount in stock</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= item.amount_in_stock %></td>
        <td><%= link_to 'Show', item %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Amount in stock:</strong>
  <%= @item.amount_in_stock %>
</p>

<%= link_to 'Back', items_path %>
<% if @item.amount_in_stock > 0 %>
  <%= button_to 'Buy now', item_purchases_path(@item) %>
<% else %>
  <%= button_to 'Create stock alert', item_stock_alerts_path(@item) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatsInc</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/stock_alerts/show.html.erb
<p>
  <strong>Item:</strong>
  <%= @stock_alert.item.name %>
</p>

<%= link_to 'Remove', @stock_alert, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', item_path(@stock_alert.item) %>